# Generated by Django 2.0.3 on 2018-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.IntegerField(verbose_name='Дом')),
                ('apartment', models.CharField(max_length=15, verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='AppTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=15, verbose_name='Название типа')),
                ('abbr', models.CharField(max_length=3, verbose_name='Абревиатура типа')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='problem',
            field=models.CharField(max_length=2048, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='application',
            name='types',
            field=models.ForeignKey(on_delete='', to='application.AppTypes', verbose_name='Тип'),
        ),
    ]
