# Generated by Django 2.0.3 on 2018-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180328_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.ForeignKey(on_delete='', to='application.Apartment', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house',
            field=models.CharField(max_length=5, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='street',
            name='street',
            field=models.CharField(max_length=256, verbose_name='Улица'),
        ),
    ]
