# Generated by Django 2.0.3 on 2018-03-28 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20180328_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='activation',
            field=models.BooleanField(verbose_name='активация'),
        ),
        migrations.AlterField(
            model_name='application',
            name='master',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='router',
            field=models.BooleanField(verbose_name='Роутер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='router_pro',
            field=models.BooleanField(verbose_name='Роутер ПРО'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.CharField(max_length=256, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='application',
            name='telephone',
            field=models.CharField(max_length=256, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tuner',
            field=models.BooleanField(verbose_name='Тюнер'),
        ),
    ]
