# Generated by Django 2.0.3 on 2018-03-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180328_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsuccess',
            options={'verbose_name': 'Тип работы', 'verbose_name_plural': 'Тип работ'},
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Комментарий отчета'),
        ),
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='error',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='application.AppError', verbose_name='Причины'),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_router',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Серийник роутера'),
        ),
        migrations.AlterField(
            model_name='application',
            name='num_tuner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC тюнера'),
        ),
        migrations.AlterField(
            model_name='application',
            name='success',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='application.AppSuccess', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='appsuccess',
            name='success',
            field=models.CharField(max_length=15, verbose_name='Тип работы'),
        ),
    ]
