# Generated by Django 2.0.3 on 2018-03-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20180328_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='problem',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Проблема'),
        ),
    ]
